### ISSUE TITLE
Pact-message.bat builds empty nodes in pact written to disc

### ISSUE THREAD

**Issue by mattermack** [pact-foundation/pact-ruby-standalone#20]
Version: 1.47.1

When running pact-message.bat, contents and metadata are not populated.

Example
```
D:\Development\github\pact-php>pact-message.bat update '{"description":"an alligator named Mary exists","providerState":"a hello message","metadata":{"queue":"wind cries"},"contents":{"text":"Hello Mary"}}' --consumer=test --provider=testp --pact-dir='D:\\Temp\\'
```

Produces
```
{
  "consumer": {
    "name": "test"
  },
  "provider": {
    "name": "testp"
  },
  "messages": [
    {
      "description": "an alligator named Mary exists",
      "providerStates": [
        {
          "name": "a hello message"
        }
      ],
      "content": null,
      "matchingRules": {
        "body": {
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

It would seem to me we should not have matchingRules and have messages[{metadata: and messages[{contents: not null

Am I missing something?

**Comment by bethesque** [comment]
Is it only on windows?

**Comment by bethesque** [comment]
Tre "contents", not "content".

**Comment by bethesque** [comment]
Oh, you did. Sorry. I'm not sure why it's writing to content instead. @mefellows has it working. Let me investigate.

**Comment by bethesque** [comment]
Ok! Turns out that I wasn't even writing the metadata. I've added it in. Here's the output from one of my tests.

```
bundle exec bin/pact-message update '{
  "description": "a test mesage",
  "contents": {
    "name": {
      "contents": "Mary",
      "json_class": "Pact::SomethingLike"
    }
  }
}
' --consumer Foo --provider Bar --pact-dir ./tmp
{
  "consumer": {
    "name": "Foo"
  },
  "provider": {
    "name": "Bar"
  },
  "messages": [
    {
      "description": "a test mesage",
      "contents": {
        "name": "Mary"
      },
      "matchingRules": {
        "body": {
          "$.name": {
            "match": "type"
          }
        }
      },
      "metaData": {
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}
```

I don't know why the content is not there. It's like that's a really old version of pact-message. I'll check what's in the standalone.

**Comment by bethesque** [comment]
I've released and tested the latest standalone. Grab v 1.47.3

**Comment by mattermack** [comment]
Thanks, Beth.  I'll check it out, likely in a few days (probably Monday in
Austin)

**Comment by mattermack** [comment]
Validated!  Thanks, Beth.

As an fyi, I still get a matchingRules.body object, despite not passing in any matching rules.   This does not seem to harm anything.

**Comment by bethesque** [comment]
Yeah, that's expected.

**Comment by bethesque** [comment]
You wouldn't pass in matching rules, as the easiest way is to use the old Ruby syntax anyway. The matching rules are generated.
